import "dotenv/config";

// THIS FILE IS AUTOGENERATED. IF YOU WANT TO SETUP CONFIG USE BUILTIN EDITOR

// JK DON'T USE BUILTIN CONFIG
// USE A .env FILE, BUILTIN CONFIG WILL PROBABLY BREAK THIS

export default {
    "token": process.env.TOKEN || "",
    "audioLengthSeconds": "5"
}